name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  plan:
    if: "contains(github.event.head_commit.message, 'terraform')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.4.6"

      - name: Terraform Init
        working-directory: ./terraform
        run: ls && terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=plan

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: plan

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.4.6"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: plan
          path: .

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply plan